name: ollama-docker
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    pull_policy: never
    ports:
      - "127.0.0.1:11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped

volumes:
  ollama:
